### ISSUE TITLE
revisions table not null violation on id column (default primary key)

### ISSUE THREAD

**Issue by DavidOliver** [Qqwy/elixir_revisionair_ecto#41]
Hi, and thanks for Revisionair!

I think I'm pretty much set up with it in my project now, but have a question on the revisions table creation/migration, please.

If I use the example migration as is, the revisions table is created with an `id` column, and attempting to store a revision results in a not null violation on it. If I instead use `create table(:revisions, primary_key: false) do` in the migration, revisions are successfully stored.

Is creating the table without a default primary key necessary/the correct thing to do, or is there something screwy going on?

**Comment by Qqwy** [comment]
Great question!

It is indeed not necessary to give the revisions table itself an `id` column, since `item_type + item_id + revision` is used as (primary) index; I'll edit the README and the tests to reflect this.
**EDIT:** Version 1.2.1 has now been released with this change (no change in behaviour, but a change in README + tests)

However, I wonder what is going wrong in your particular set-up, since (at least locally) the tests run without problems.

What version of Ecto and Postgres (or another DB?) are you using?
Could you try cloning the repository + running the tests on your machine, maybe?

**Comment by DavidOliver** [comment]
Thanks for the response. :) I'll clone and run the tests soon.

I checked the query debug output when running the Phoenix server, and there was no `id` in the insert statement.

**Comment by Qqwy** [comment]
For most databases, the built-in primary ID will be prefilled (by the DB) with an auto-incrementing integer, so Ecto would indeed not specify it.
What database (and what version of it) are you using?

**Comment by DavidOliver** [comment]
Ah, is it because I'm using UUIDs for Ecto-created default id columns? I'm guessing Ecto itself generates a new UUID when creating a new entry, but that that isn't happening for revision storing.

Based on a quick search, [this extension](http://www.ossp.org/pkg/lib/uuid/) is required to allow PostgreSQL to create UUIDs itself.

I ran the tests for both the commit I was on and the latest, and all passed. I'm running PostgreSQL 12.3.

Thanks for the quick response and the migration update!

**Comment by Qqwy** [comment]
Thank you very much! Great to hear that it now works, as well as the probable reason why it might not have at first.

:green_heart:
